// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using blog_server.Data;

#nullable disable

namespace blog_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322164420_FixAuth")]
    partial class FixAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("blog_server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator role",
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "User role",
                            Name = "USER"
                        });
                });

            modelBuilder.Entity("blog_server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96cb39f1-318f-4b17-97fb-c9bffe823a98"),
                            Email = "admin@example.com",
                            PasswordHash = "bkt/JODEdbDR7FJS1xi+k/aBshLu9spXfRSSBg/qS6CrxMlv6tqfMFEy1+OWljK2ivcw/aonZLOX5WhEDwoHoj9bqowtwSKsNz9SDfjlcyY=",
                            Status = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("19542f2e-d222-4a24-a786-c2dc08ccfd87"),
                            Email = "user@example.com",
                            PasswordHash = "y5k3YlEFB8xQCTElrM/knK5Pp7D5U23elJkXeCMKvpQLBefp6SrR7N37cKs8BZhU7FbS990e/dq2k1EIsJXEQ+WIfPk0luYV7cnO7zLwPS0=",
                            Status = 1,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("blog_server.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_date");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("96cb39f1-318f-4b17-97fb-c9bffe823a98"),
                            RoleId = 1,
                            JoinDate = new DateTime(2025, 3, 22, 16, 44, 20, 545, DateTimeKind.Utc).AddTicks(720)
                        },
                        new
                        {
                            UserId = new Guid("19542f2e-d222-4a24-a786-c2dc08ccfd87"),
                            RoleId = 2,
                            JoinDate = new DateTime(2025, 3, 22, 16, 44, 20, 545, DateTimeKind.Utc).AddTicks(720)
                        });
                });

            modelBuilder.Entity("blog_server.Models.UserRole", b =>
                {
                    b.HasOne("blog_server.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("blog_server.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("blog_server.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("blog_server.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
